### ISSUE TITLE
can't import anything with 0.5.0

### ISSUE THREAD

**Issue by macrozone** [Galooshi/atom-import-js#11]
after upgrading to 0.5.0 I can't import anything anymore. I always receive "No JS module to import for ...."

I can't downgrade the package in atom, so i am a little bit lost now :-(

**Comment by macrozone** [comment]
ok i downgraded to 0.3.0 and it works again.

0.4.3. did also not work, i got the error "Cannot find module 'import-js/build/WatchmanFileCache'"

**Comment by trotzig** [comment]
Sorry about that! A few questions that might help me nail down the issue: 
- Do you have watchman installed? https://facebook.github.io/watchman/
- Does your project contain a package.json file in the root folder?

**Comment by trotzig** [comment]
@macrozone we're you able to find anything more related to this?

**Comment by macrozone** [comment]
Hi, sorry hadn't had the time yet, will try to install watchman

Henric Trotzig <notifications@github.com> schrieb am Di., 7. Feb. 2017,
20:15:

**Comment by macrozone** [comment]
ok, installed watchman (with brew), updated atom-import-js to 0.5.0 , opened a folder with atom (the folder where the package.json is) and still can't import anything. Nothing is found. Is there a debug log or anything?

Downgraded now again to 0.3.0

**Comment by trotzig** [comment]
Logs will go to a file called import-js.log in the default tmp directory of your os. If you install `import-js` directly (`npm install -g import-js`) you can use `importjs logpath` to get a full path to the logfile. 

In your `.importjs.js` config, you can add `logLevel: 'debug'` for some more verbose logging. 

I appreciate you helping out here. Version 0.5.0 rewrites a lot of the core of import-js. Before, it would look directly in the file system for imports. Now, we keep a cache of all the files and their imports. We do this so that we can find named exports inside files. The caching strategy is definitely more complex, and I'm sorry that it's causing you headaches. With your help however, I hope we can nail down the issue and fix the bug so that others can benefit!

Let me know what's in the logs after trying out an import.

**Comment by trotzig** [comment]
I looked into the non-watchman support, and found a few issues that I've addressed in https://github.com/Galooshi/import-js/pull/367. I'm still interested to hear if you're seeing anything from the logs though.

**Comment by macrozone** [comment]
It works now with 0.5.1. I made sure that import-js was also installed globally. It's not clear from the readme whether this is required though. Thank you for your efforts!

**Comment by trotzig** [comment]
Glad it's working! I updated the readme slightly to help make it more clear that a global import-js install isn't necessary.
